// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmgzwxqrfawknamqtxfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZ3p3eHFyZmF3a25hbXF0eGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mjc0NDcsImV4cCI6MjA2MjIwMzQ0N30.ASQ17GmI2q5xx8_rYUdFiFgUaj2oBdjhOp-igt4x-BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);